services:
  postgres:
    image: postgres:15
    container_name: counter-postgres
    environment:
      POSTGRES_DB: counter_db
      POSTGRES_USER: counter_user
      POSTGRES_PASSWORD: counter_pass
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: